name: job ex6
on: 
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  run-npm-install:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        node: ['12', '14', 'lts/*']
        exclude:
          - os: ubuntu-18.04
            node: '12'
    runs-on: ${{ matrix.os }}
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node }}
        - name: run install
          shell: bash
          run: |
            npm ci
        - name: Cache node modules
          uses: actions/cache@v3
          env:
            cache-name: cache-node-modules
          with:
            path: ./node_modules
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-

  run-npm-test:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        node: ['12', '14', 'lts/*']
        exclude:
          - os: ubuntu-18.04
            node: '12'
    runs-on: ${{ matrix.os }}
    needs: run-npm-install
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node }}
        - name: Cache node modules
          uses: actions/cache@v3
          env:
            cache-name: cache-node-modules
          with:
            path: ./node_modules
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
        - name: run test
          shell: bash
          run: |
            npm test
    
  build-docker-image:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        node: ['12', '14', 'lts/*']
        exclude:
          - os: ubuntu-18.04
            node: '12'
    runs-on: ${{ matrix.os }}
    needs: run-npm-test
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name : setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: print current branch name
        run: |
          echo "${github.ref}"
      - name: build docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t {{ github.sha }} .