name: job ex6
on: 
  workflow_dispatch:

env:
  node-version: 16

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: ${{ env.node-version }}
        - name: run install
          shell: bash
          run: |
            npm ci
        - name: Cache node modules
          uses: actions/cache@v3
          env:
            cache-name: cache-node-modules
          with:
            path: ~/node_modules
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-

  run-npm-test:
    runs-on: ubuntu-latest
    needs: run-npm-install
    steps:
        - name: checkout
          uses: actions/checkout@v2
        - name : setup node
          uses: actions/setup-node@v2
          with:
            node-version: ${{ env.node-version }}
        - name: run test
          shell: bash
          run: |
            npm test